### ISSUE TITLE
not working with videojs8 / modern javascript?

### ISSUE THREAD

**Issue by ttyridal** [7Ds7/videojs-vjsdownload#7]
```
videojs-vjsdownload.js:45 Uncaught TypeError: Class constructor s cannot be invoked without 'new'
    at new DownloadButton (videojs-vjsdownload.js:45:80)
    at onPlayerReady (videojs-vjsdownload.js:92:44)
    at b.<anonymous> (videojs-vjsdownload.js:117:5)
    at b.<anonymous> (videojs_8_3_0.min.js:12:24999)
    at Array.forEach (<anonymous>)
    at b.<anonymous> (videojs_8_3_0.min.js:12:24977)
    at videojs_8_3_0.min.js:12:27660
```

**Comment by 7Ds7** [comment]
fixed in [v2](https://github.com/7Ds7/videojs-vjsdownload/releases/tag/2.0.0) although the 1.0.5 version works properly with videojs 8 at least on my end. Please let me know if version 2 fixes things for you
